import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import "./globals.css";

import { Cairo } from "next/font/google";

// const inter = Inter({ subsets: ["latin"] });
const cairo = Cairo({
  subsets: ["latin", "arabic"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Mashrook",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cairo.className}>
        <div className="flex items-center justify-center min-h-screen bg-[#DCE9E5]">
          <div className="w-full lg:w-1/2 ">{children}</div>
        </div>
      </body>
    </html>
  );
}
